/*
 * registry.c — Module list management (ELF section-based discovery).
 */

#include "agent_framework.h"
#include "framework_internal.h"
#include "os_api.h"

framework_registry_t g_registry = {0};

/* ELF section boundary symbols — auto-generated by linker.
   Triple underscore: __start___ followed by section name (dots become underscores). */
extern char __start___agent_modules[];
extern char __stop___agent_modules[];

void _fw_module_register(framework_module_t *mod)
{
    if (!mod || !mod->name) return;
    if (g_registry.count >= MAX_MODULES) {
        os_fprintf_stderr("Framework: max modules (%d) reached, ignoring '%s'\n",
                          MAX_MODULES, mod->name);
        return;
    }
    mod->state = FRAMEWORK_STATE_UNLOADED;
    g_registry.list[g_registry.count++] = mod;
}

int framework_discover_modules(void)
{
    /* Scan the .agent_modules section: array of framework_module_t pointers */
    framework_module_t **p = (framework_module_t **)__start___agent_modules;
    framework_module_t **end = (framework_module_t **)__stop___agent_modules;

    for (; p < end; p++) {
        if (*p && (*p)->name) {
            _fw_module_register(*p);
        }
    }

    return g_registry.count;
}


framework_module_t *framework_get_module_by_index(unsigned int index)
{
    if (index >= (unsigned)g_registry.count) return NULL;
    return g_registry.list[index];
}

framework_module_t *framework_get_module_by_name(const char *name)
{
    if (!name) return NULL;
    for (int i = 0; i < g_registry.count; i++) {
        framework_module_t *mod = g_registry.list[i];
        if (mod->name && os_strcmp(mod->name, name) == 0) {
            return mod;
        }
    }
    return NULL;
}
